# Site title and subtitle. This is used in _includes/header.html
title: 'WP-Palvelu.fi Docs'
subtitle: 'Documentation for Developers'

# Titile to show in footer
footer_title: WP-Palvelu.fi

# Link to Github repo
# This is used in editing links
github:
    repo: WP-Palvelu/developer-documentation

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-53086901-9'

# Site verification for webmasters
google_site_verification: "urAsJ1u3OTw8C7-KQnc2GxU7rJb7i4DAbbPxUv-eT9k"

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 1

# URL to source code, used in _includes/footer.html
codeurl: 'https://wp-palvelu.fi'

# Default categories (in order) to appear in the navigation
sections: [
    ['get-started', 'Get Started'],
    ['configuration', 'Configuration'],
    ['tests', 'Testing'],
    ['development', 'Development'],
    ['deployment', 'Deployment'],
    ['management', 'Management']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# This is used in <meta> og fields
siteurl: http://docs.wp-palvelu.fi

# Use sass from assets folder
sass:
  sass_dir: /assets/_sass
  style: :compressed

# Additional gems to use
gems:
  - jekyll-sitemap # Generates sitemaps for Google

# Dates are not included in permalinks
permalink: /:categories/:title/

# Syntax highlighting
highlighter: pygments

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin','CNAME', 'README.md']

# Use the redcarpet Markdown renderer
markdown: redcarpet
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]

##
# Prose settings
##
prose:
  rooturl: '_posts'
  siteurl: 'http://docs.wp-palvelu.fi'
  media: 'media'
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
    - assets
    - /bin
    - /_pages
    - CNAME
    - search.json
    - bower.json
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "category"
        field:
          element: "select"
          label: "Add Category"
          placeholder: "Pick a category"
          alterable: true # User can add new categories
          options: 
            - 
              name: "Get Started"
              value: get-started
            - 
              name: "Configuration"
              value: configuration
            - 
              name: "Testing"
              value: tests
            - 
              name: "Development"
              value: development
            - 
              name: "Deployment"
              value: deployment
            - 
              name: "Management"
              value: management
              
      - name: "order"
        field:
          element: "number"
          label: Page order in the category
          help: You can order pages with this
          value: 1
          type: "number"